### ISSUE TITLE
Import using typescript

### ISSUE THREAD

**Issue by guumo** [Vicnovais/odata-sequelize#17]
When try to use typescript to import typescript generate this error.

"This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export."

Thanks

**Comment by Vicnovais** [comment]
Please, double check if the option `esModuleInterop` is set for `true` in your tsconfig.json.
If this seems right, please refer to stackoverflow, this does not seem a bug with this package.
If you have any more doubts, please answer this issue.

Reference: [https://stackoverflow.com/questions/68785926/this-module-can-only-be-referenced-with-ecmascript-imports-exports-by-turning-on](https://stackoverflow.com/questions/68785926/this-module-can-only-be-referenced-with-ecmascript-imports-exports-by-turning-on)
