### ISSUE TITLE
Functions Error

### ISSUE THREAD

**Issue by haydar-can** [Vicnovais/odata-sequelize#6]
1) Function Comparison not working
oData
```odata : ...?$filter=year(OrderDate) gt '2016'```

sequelize generated MSSQL sentece in WHERE:
```year([OrderDate]) = N'2016'```

my expected:
```year([OrderDate]) > N'2016'```

always run eq..

2)Error : Function fieldName not working:
```"Invalid column name 'OrderDate'.",```

Model:
```
OrderDate: {
			type: Sequelize.DataTypes.DATEONLY,
			allowNull:false,
			unique:true,
			primaryKey:true,
			field:'Order Date' //my defination
		}
```

**Comment by Vicnovais** [comment]
It'll be fixed in next release in the next days.

**Comment by Vicnovais** [comment]
The first issue is fixed now. I could not understand the second one, it looks like it's an error in your sequelize configuration. Can you provide some more info?

Thanks.

**Comment by haydar-can** [comment]
The column name definition in the table in MSSQL Server has two words (in the definition in the example above, "field: 'Order Date'), but it is defined as a word in my definition for ORM (
```orderdate {
...
field: 'Order Date'
}
```
For this reason, even though I use a word in the ODATA sentence, it is also generated as a word in the SQL statement. For this reason, I get the wrong column name error.
